[package]
name = "phosphor-gpui"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "Phosphor Icons for GPUI and GPUI Kit."
repository = "https://github.com/AkaraChen/phosphor-gpui"
readme = "README.md"
keywords = ["gpui", "icons", "phosphor"]
categories = ["gui"]
build = "build.rs"
include = [
	"src/**",
	"assets/regular/**",
	"build.rs",
	"README.md",
	"LICENSE",
	"LICENSE-PHOSPHOR",
	"phosphor.json",
]

[lib]
doctest = false

[dependencies]
anyhow = "1"
gpui = { version = "0.3", package = "gpui-pre" }
gpui-kit-assets = "0.6"

[target.'cfg(not(target_family = "wasm"))'.dependencies]
rust-embed = { version = "8.7.2", features = [
	"interpolate-folder-path",
	"include-exclude",
] }
