// Lucide default-icon stems that are not Phosphor file names.
// Generated from gpui-kit-assets 0.6.1 default-icons.txt.

pub const LUCIDE_OVERRIDES: &[(&str, &str)] = &[
	("a-large-small", "text-aa"),
	("battery", "battery-empty"),
	("bot", "robot"),
	("building-2", "buildings"),
	("case-sensitive", "text-aa"),
	("chevron-down", "caret-down"),
	("chevron-left", "caret-left"),
	("chevron-right", "caret-right"),
	("chevron-up", "caret-up"),
	("chevrons-up-down", "caret-up-down"),
	("circle-check", "check-circle"),
	("circle-user", "user-circle"),
	("circle-x", "x-circle"),
	("close", "x"),
	("dash", "minus"),
	("delete", "backspace"),
	("ellipsis", "dots-three"),
	("ellipsis-vertical", "dots-three-vertical"),
	("external-link", "arrow-square-out"),
	("eye-off", "eye-slash"),
	("folder-closed", "folder"),
	("frame", "selection"),
	("gallery-vertical-end", "rows"),
	("github", "github-logo"),
	("heart-off", "heart-break"),
	("inbox", "tray"),
	("inspector", "magnifying-glass-plus"),
	("layout-dashboard", "squares-four"),
	("loader", "spinner-gap"),
	("loader-circle", "spinner"),
	("map", "map-trifold"),
	("maximize", "arrows-out"),
	("memory-stick", "circuitry"),
	("menu", "list"),
	("minimize", "arrows-in"),
	("network", "graph"),
	("panel-bottom", "sidebar"),
	("panel-bottom-open", "sidebar"),
	("panel-left", "sidebar-simple"),
	("panel-left-close", "sidebar-simple"),
	("panel-left-open", "sidebar-simple"),
	("panel-right", "sidebar"),
	("panel-right-close", "sidebar"),
	("panel-right-open", "sidebar"),
	("redo", "arrow-clockwise"),
	("redo-2", "arrow-clockwise"),
	("replace", "arrows-left-right"),
	("resize-corner", "arrows-out-cardinal"),
	("rotate-cw", "arrow-clockwise"),
	("search", "magnifying-glass"),
	("settings", "gear"),
	("settings-2", "sliders-horizontal"),
	("square-terminal", "terminal-window"),
	("star-fill", "star"),
	("star-off", "star"),
	("triangle-alert", "warning"),
	("undo", "arrow-counter-clockwise"),
	("undo-2", "arrow-counter-clockwise"),
	("window-close", "x"),
	("window-maximize", "square"),
	("window-minimize", "minus"),
	("window-restore", "copy"),
];

pub fn lucide_stem(stem: &str) -> &str {
	match LUCIDE_OVERRIDES.binary_search_by_key(&stem, |&(key, _)| key) {
		Ok(ix) => LUCIDE_OVERRIDES[ix].1,
		Err(_) => stem,
	}
}
